DECLARE
  VSK_PARTIDA NUMBER;
BEGIN
  VSK_PARTIDA := LABDATABASE.SCOUTS_PARTIDA_SK_PARTIDA_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.SCOUTS_PARTIDA (SK_PARTIDA, QUANTIDADE, CARTAO_VERMELHO, CARTAO_AMARELO, FALTAS, LATERAIS, ESCANTEIOS, GOLS, ASSISTENCIA)
  VALUES (VSK_PARTIDA, 1, 1, 1, 27, 50, 14, 0, 0);

  INSERT INTO LABDATABASE.PARTIDAS (SK_PARTIDA, TIME_CASA, TIME_VISITANTE, GOLS_PRO, GOLS_CONTRA, ARBITRO, ESTADIO)
  VALUES (VSK_PARTIDA, 'Fluminense', 'Flamengo', 0, 0, 'Anderson Daronco', 'Maracanã');

  COMMIT;
END;

DECLARE
  VSK_TIMES NUMBER;
BEGIN
  VSK_TIMES := LABDATABASE.TIMES_SK_TIMES_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.TIMES (SK_TIMES, NOME, CORES, TREINADOR, SK_PARTIDA)
  VALUES (VSK_TIMES, 'Fluminense', 3, 'Fernando Diniz', VSK_PARTIDA);

  COMMIT;
END;

DECLARE
  VSK_TIMES NUMBER;
BEGIN
  VSK_TIMES := LABDATABASE.TIMES_SK_TIMES_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.TIMES (SK_TIMES, NOME, CORES, TREINADOR, SK_PARTIDA)
  VALUES (VSK_TIMES, 'Flamengo', 2, 'Tite', VSK_PARTIDA);

  COMMIT;
END;

DECLARE
  VSK_ATLETAS NUMBER;
BEGIN
  VSK_ATLETAS := LABDATABASE.ATLETAS_SK_ATLETAS_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.ATLETAS (SK_ATLETAS, NOME, NUMERO, POSICAO, CARTAO_AMARELO, CARTAO_VERMELHO, DESCRICAO, SK_PARTIDA, SK_TIMES)
  VALUES (VSK_ATLETAS, 'Marcelo', 12, 'LE', 4, 1, 'O brasileiro já foi elogiado por grandes ex-jogadores como Paolo Maldini e Diego Maradona, que o considerou o melhor de sua posição', 1, 1);

  COMMIT;
END;

DECLARE
  VSK_ATLETAS NUMBER;
BEGIN
  VSK_ATLETAS := LABDATABASE.ATLETAS_SK_ATLETAS_SEQ.NEXTVAL;

  INSERT INTO LABDATABASE.ATLETAS (SK_ATLETAS, NOME, NUMERO, POSICAO, CARTAO_AMARELO, CARTAO_VERMELHO, DESCRICAO, SK_PARTIDA, SK_TIMES)
  VALUES (VSK_ATLETAS, 'Bruno Henrique', 27, 'AT', 6, 0, 'Bruno Henrique Pinto é um futebolista brasileiro que atua como atacante. Atualmente, defende o Flamengo.', 1, 1);

  COMMIT;
END;